## Data-X(IEOR 290): HW 2
### Tu Ni
#### SID: 3032165865

# Problem 1

In [2]:
import numpy as np

Q1

In [3]:
a = np.arange(10,20)

In [4]:
b = np.linspace(1,7,10)

In [5]:
print (a**2)
print (b**2)

[100 121 144 169 196 225 256 289 324 361]
[  1.           2.77777778   5.44444444   9.          13.44444444
  18.77777778  25.          32.11111111  40.11111111  49.        ]


In [6]:
add = a**2 + b**2
print (add)

[ 101.          123.77777778  149.44444444  178.          209.44444444
  243.77777778  281.          321.11111111  364.11111111  410.        ]


In [8]:
print (sum(add[::2]))

1105.0


In [10]:
print (add ** 0.5)

[ 10.04987562  11.12554618  12.22474721  13.34166406  14.47219556
  15.61338457  16.76305461  17.91957341  19.08169571  20.24845673]


Q2

In [9]:
m = np.append(a,b).reshape(5,4)
print (m)

[[ 10.          11.          12.          13.        ]
 [ 14.          15.          16.          17.        ]
 [ 18.          19.           1.           1.66666667]
 [  2.33333333   3.           3.66666667   4.33333333]
 [  5.           5.66666667   6.33333333   7.        ]]


Q3

In [10]:
m2 = m[:,1:3]
print (m2)

[[ 11.          12.        ]
 [ 15.          16.        ]
 [ 19.           1.        ]
 [  3.           3.66666667]
 [  5.66666667   6.33333333]]


Q4

In [11]:
m3 = np.dot(np.transpose(m2), m)
print (m3)

[[ 697.33333333  748.11111111  437.88888889  482.33333333]
 [ 402.22222222  437.88888889  454.55555556  489.88888889]]


Q5

In [12]:
m3 = np.round(m3,2)
print (m3)

[[ 697.33  748.11  437.89  482.33]
 [ 402.22  437.89  454.56  489.89]]


Q6

In [17]:
print (np.sort(m3,axis = None)[::-1].reshape(2,4))

[[ 748.11  697.33  489.89  482.33]
 [ 454.56  437.89  437.89  402.22]]
